print("##############################\n")
print("#                            #\n")
print("# Jovan Gilbert Natamasindah #\n")
print("#       2310817310002        #\n")
print("#                            #\n")
print("##############################\n")