INSERT INTO mata_kuliah (nama_matkul) VALUES
('Bahasa Inggris I'),
('Bahasa Indonesia'),
('Pemrograman I'),
('Pemrograman II'),
('Pemrograman Web I'),
('Pemrograman Web II'),
('Pemrograman Mobile'),
('Analisis Perancangan Sistem'),
('Administrasi Sistem dan Jaringan'),
('Basis Data I'),
('Basis Data II'),
('Algoritma dan Struktur Data'),
('Jaringan Komunikasi dan Data'),
('Statistika dan Probabilitas'),
('Matematika Diskrit'),
('Kalkulus'),
('Aljabar Linear'),
('Sistem Operasi'),
('Rekayasa Perangkat Lunak'),
('Keamanan Siber');
